In [50]:
import pandas as pd
df=pd.read_csv('IMDb_All_Genres_etf_clean1.csv')
df.head()

,Movie_Title,Year,Director,Actors,Rating,Runtime(Mins),Censor,Total_Gross,main_genre,side_genre
0,Kantara,2022,Rishab Shetty,"Rishab Shetty, Sapthami Gowda, Kishore Kumar G...",9.3,148,UA,Gross Unkown,Action,"Adventure, Drama"
1,The Dark Knight,2008,Christopher Nolan,"Christian Bale, Heath Ledger, Aaron Eckhart, M...",9.0,152,UA,$534.86M,Action,"Crime, Drama"
2,The Lord of the Rings: The Return of the King,2003,Peter Jackson,"Elijah Wood, Viggo Mortensen, Ian McKellen, Or...",9.0,201,U,$377.85M,Action,"Adventure, Drama"
3,Inception,2010,Christopher Nolan,"Leonardo DiCaprio, Joseph Gordon-Levitt, Ellio...",8.8,148,UA,$292.58M,Action,"Adventure, Sci-Fi"
4,The Lord of the Rings: The Two Towers,2002,Peter Jackson,"Elijah Wood, Ian McKellen, Viggo Mortensen, Or...",8.8,179,UA,$342.55M,Action,"Adventure, Drama"

In [51]:
#lazim olan sutunlari secek
secilmis_data=df[['Movie_Title','Director','main_genre','side_genre']]
secilmis_data.head(5)

,Movie_Title,Director,main_genre,side_genre
0,Kantara,Rishab Shetty,Action,"Adventure, Drama"
1,The Dark Knight,Christopher Nolan,Action,"Crime, Drama"
2,The Lord of the Rings: The Return of the King,Peter Jackson,Action,"Adventure, Drama"
3,Inception,Christopher Nolan,Action,"Adventure, Sci-Fi"
4,The Lord of the Rings: The Two Towers,Peter Jackson,Action,"Adventure, Drama"

In [52]:
secilmis_data['tags']=secilmis_data['main_genre']+" "+secilmis_data['side_genre']
secilmis_data[['Movie_Title','tags']].head()

C:\Users\T.T_S\AppData\Local\Temp\ipykernel_2840\3287697073.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  secilmis_data['tags']=secilmis_data['main_genre']+" "+secilmis_data['side_genre']

                                     Movie_Title                        tags
0                                        Kantara   Action  Adventure,  Drama
1                                The Dark Knight       Action  Crime,  Drama
2  The Lord of the Rings: The Return of the King   Action  Adventure,  Drama
3                                      Inception  Action  Adventure,  Sci-Fi
4          The Lord of the Rings: The Two Towers   Action  Adventure,  Drama

In [53]:
#vergulleri evez edek bosluqla
secilmis_data['tags'] = secilmis_data['tags'].str.replace(',', ' ').str.lower()
secilmis_data

C:\Users\T.T_S\AppData\Local\Temp\ipykernel_2840\237598419.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  secilmis_data['tags'] = secilmis_data['tags'].str.replace(',', ' ').str.lower()

,Movie_Title,Director,main_genre,side_genre,tags
0,Kantara,Rishab Shetty,Action,"Adventure, Drama",action adventure drama
1,The Dark Knight,Christopher Nolan,Action,"Crime, Drama",action crime drama
2,The Lord of the Rings: The Return of the King,Peter Jackson,Action,"Adventure, Drama",action adventure drama
3,Inception,Christopher Nolan,Action,"Adventure, Sci-Fi",action adventure sci-fi
4,The Lord of the Rings: The Two Towers,Peter Jackson,Action,"Adventure, Drama",action adventure drama
...,...,...,...,...,...
5557,Disaster Movie,"Directors:Jason Friedberg, Aaron Seltzer",Comedy,Sci-Fi,comedy sci-fi
5558,The Hottie & the Nottie,Tom Putnam,Comedy,Romance,comedy romance
5559,From Justin to Kelly,Robert Iscove,Comedy,"Musical, Romance",comedy musical romance
5560,Superbabies: Baby Geniuses 2,Bob Clark,Comedy,"Family, Sci-Fi",comedy family sci-fi
5561,Cumali Ceber: Allah Seni Alsin,Gökhan Gök,Comedy,Comedy,comedy comedy

In [54]:
#janrlari  komputerin basa duseceyi dile cevirek
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000,stop_words='english') #ingilis dilindeki stop(in at,the ve s.)sozleri goturur dayanir lugtee elave etmir
vectors=cv.fit_transform(secilmis_data['tags']).toarray()
print("Vektorlaşdırma bitdi! ✅")
print("Vektorun ölçüsü:", vectors.shape)

Vektorlaşdırma bitdi! ✅
Vektorun ölçüsü: (5562, 25)

In [61]:
secilmis_data.loc[:, 'Movie_Title'] = secilmis_data['Movie_Title'].str.lower()

def tovsiye_et():
    film_adi = input("Baxdığınız filmin adını daxil edin: ").lower()     
    try:
        # Axtarış
        film_index = secilmis_data[secilmis_data['Movie_Title'] == film_adi].index[0]
        
        mesafeler = similarity[film_index]
        film_list = sorted(list(enumerate(mesafeler)), reverse=True, key=lambda x: x[1])[1:6]
        
        print(f"\n✅ '{film_adi.title()}' tapıldı! Tövsiyələrimiz:\n")
        for i in film_list:
            # .title() hər sözün baş hərfini böyüdür, daha gözəl görünür
            print(f"🎬 {secilmis_data.iloc[i[0]].Movie_Title.title()}")
            
    except IndexError:
        print(f"\n❌ '{film_adi}' adlı film bazada tapılmadı.")

# Çağırırıq
tovsiye_et()

Baxdığınız filmin adını daxil edin:  disaster movie

✅ 'Disaster Movie' tapıldı! Tövsiyələrimiz:

🎬 Frequently Asked Questions About Time Travel
🎬 Uhf
🎬 Hot Tub Time Machine
🎬 Mars Attacks!
🎬 Evolution